export const projects = [
   {
      title: "Volfi Productfinder",
      description:
         "Used Vanilla JavaScript, HTML, CSS & a Rest API to build a Product finder Web Application - The Web-App works on Mobile, Tablet, and Desktop devices and helps the user find the right product for his needs.",
      image: "/images/produktfinder.jpg",
      tags: ["JavaScript", "HTML", "CSS", "JSON"],
      source: "https://google.com",
      visit: "https://produktfinder.pluggramming.de/",
      id: 0,
   },
   {
      title: "Netzhero",
      description: "This Website is the Web Identity of my side hustle 'Netzhero' and is a small showcase of what services I provided to my customers. It was built with a Bootstrap Theme.",
      image: "/images/netzhero.jpg",
      tags: ["JavaScript", "PHP", "HTML", "CSS", "Bootstrap"],
      source: "https://google.com",
      visit: "https://netzhero.de/",
      id: 1,
   },
   {
      title: "Psychotherapie Lennestadt",
      description: "This Website was built with WordPress so that the owners can maintain it easily by themselves. It was important that potential clients can contact the psychologist.",
      image: "/images/psychotherapielennestadt.jpg",
      tags: ["WordPress", "CSS"],
      source: "https://google.com",
      visit: "https://psychotherapie-lennestadt.de/",
      id: 1,
   },
   {
      title: "diekennstedoch",
      description: "Diekennstedoch is a local brand and the owners wanted a website that brings there joy and fun to the user. We made a conzept and developed the design after the prinzip 'Mobile First'.",
      image: "/images/diekennstedoch.png",
      tags: ["WordPress", "CSS"],
      source: "https://google.com",
      visit: "https://diekennstedoch.de/",
      id: 2,
   },
   {
      title: "Holzjupp",
      description: "Holzjupp wanted to reach more potential clients to get an advantage over their competitors. The Website shows their services and some info about their practices.",
      image: "/images/holzjupp.png",
      tags: ["WordPress", "CSS"],
      source: "https://google.com",
      visit: "http://www.holzjupp.de/",
      id: 3,
   },
   {
      title: "DamnClose Airsoft",
      description: "The Website is used to showcase an Airsoft Team and to draw more attention to the Team. I build it with WordPress and implemented a Blog section so the Team can share interesting information.",
      image: "/images/damnclose.jpg",
      tags: ["WordPress", "CSS"],
      source: "https://google.com",
      visit: "https://damnclose-airsoft.de/",
      id: 4,
   },
   {
      title: "Pluggramming",
      description: "I designed a user-friendly Website to showcase the services that pluggramming offers for their customers.",
      image: "/images/pluggramming.png",
      tags: ["WordPress", "CSS"],
      source: "https://google.com",
      visit: "https://pluggramming.de/",
      id: 5,
   },
   {
      title: "Drohnen-NRW",
      description: "The owner of Drohnen-NRW had a clear vision and a concept how his website should look like, so we took care of the technical part and implemented his vision to the web.",
      image: "/images/drohnennrw.jpg",
      tags: ["WordPress", "CSS"],
      source: "https://google.com",
      visit: "https://drohnen-nrw.de/",
      id: 6,
   },
   {
      title: "Ferienwohnung Lenne",
      description: "With this Website, we aimed to reach more potential clients and to convince them to stay at this cool holiday apartment.",
      image: "/images/ferienwohnunglenne.png",
      tags: ["WordPress", "CSS"],
      source: "https://google.com",
      visit: "https://ferienwohnung-lenne.de/",
      id: 7,
   },
];

export const TimeLineData = [
   { year: 2019, text: "Founded Netzhero as a side hustle to pursue my passion (Web-Development Business)" },
   { year: 2021, text: 'Start ILS Education "Geprüfter Web-Entwickler"' },
   { year: 2022, text: "Finished my edcuation with a grade of 1,2" },
];
